botToken: "abc"
ticketCategory: "879559524850237481"
supportChannel: "994395993506320495"
ticketSupportRole: "995183142547767346"
ticketManageRole: "995183178216128572"
ticketCount: 1
maxConcurrentTickets: 2
embed:
  color: 3051ff
  title: Support Ticket
  description: "Do you need help with anything Geode-related? Just want to ask the staff a question? Click the button below to make a ticket!"
  image: "https://cdn.discordapp.com/attachments/701549229989953576/965362566043938876/Asset_3.png"
  button:
    text: "Open support ticket"
    emoji: "ğŸŸï¸"
messages:
  welcome: "%s has opened a ticket."
  username:
    title: Panel Username
    description: "Please enter your panel username.\nIf you are not currently registered, click the button."
    buttonEmoji: "âŒ"
    default: "N/A"
  topic:
    title: Ticket Topic
    description: "Click one of the options below to select the support topic."
ticketTypes:
  technical:
    description: "Questions regarding Minecraft, Geode code servers, SQL databases, or other services provided by Geode Host."
    emoji: "ğŸ”§"
  billing:
    description: "Help with payments, orders, invoices, cancellation, or changing your resource package."
    emoji: "ğŸ’¸"
  other:
    description: "Anything else you might need help with, such as partnership, sponsorship, or reporting something."
    emoji: "ğŸ’¬"
